#! /bin/bash
[ $EUID != 0 ] && echo "error: must be root" 1>&2 && exit 1
set -ex
D=$(dirname $0)

# set root passwd to user passwd
sudo sed -i "s|^root:[^:]*:|root:$(sudo grep $USER /etc/shadow | cut -d: -f2):|" /etc/shadow

key=/etc/apt/trusted.gpg.d/signal-desktop-keyring.gpg
if [[ ! -f $key ]]; then
    wget -O- https://updates.signal.org/desktop/apt/keys.asc | \
        gpg --dearmor > $key
fi
key=/etc/apt/trusted.gpg.d/microsoft-teams-keyring.gpg
if [[ ! -f $key ]]; then
    wget -O- https://packages.microsoft.com/keys/microsoft.asc | \
        gpg --dearmor > $key
fi

for ppa in \
	ppa:kicad/kicad-6.0-releases \
	ppa:freecad-maintainers/freecad-stable \
	'deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main' \
	'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main' \
	; do
    add-apt-repository --yes --no-update $ppa
done

if [ -d /var/cache/snapd ]; then
    snaps="$(snap list | grep -v -e Name -e 'core$' | cut -d' ' -f1 | tac)"
    for i in $snaps; do
        snap remove --purge $i
    done
    rm -rf /var/cache/snapd/
fi

# APT upgrade/install/remove
apt-get remove -y --purge $(grep '^-' "$D/manifest" | sed 's/^.//')
apt-get autoremove -y
apt-get update
apt-get upgrade -y
apt-get install -y $(grep '^+' "$D/manifest" | sed 's/^.//')
apt-get autoremove -y

# clean up dead directories
rm -rf /var/lib/command-not-found
rm -rf /home/*/snap
