#! /bin/bash
D=/var/tmp/downloads
BASE=/var/tmp/virtualbox
USERNAME="$(getent passwd boyle | cut -d: -f 5 | cut -d, -f1)"
[ $EUID == 0 ] && echo "error: run as user" 1>2 && exit 1
[ $# != 1 -a $# != 2 ] && echo "$(basename $0) <win10> [product-key]" 1>&2 && exit 1
VM="$1"
KEY=$2
NCPU=$(( $(cat /proc/cpuinfo |grep -m1 siblings | cut -d: -f2 | sed 's/ //g') / 2))
MEM=$(( $(cat /proc/meminfo | grep MemTotal | cut -d' ' -f2 | cat /proc/meminfo | grep MemTotal | sed 's/  */ /g' | cut -d' ' -f2) / 1024 / 4 ))
case "$VM" in
    win10)
        [ $# != 2 ] && echo "$(basename $0): $1: missing <product-key>" 1>&2 && exit 1
        ISO="Win10_1903_V1_English_x64.iso"
        OS=Windows10_64
        ;;
    *) echo "$(basename $0): $1: expected 'win10'" 1>&2 && exit 1;;
esac

set -ex
install -m 700 -d "$BASE"
VBoxManage setproperty machinefolder "$BASE"

mkdir -p "$D"
read -sp "Password: " PASSWD
PASSWDFILE="/tmp/$(basename $0)-passwd"

trap "rm -f \"$PASSWDFILE\"" EXIT
touch "$PASSWDFILE"
chmod go-rwx "$PASSWDFILE"
set +x
echo "$PASSWD" > "$PASSWDFILE"
set -x

FF_URL="https://cdn.stubdownloader.services.mozilla.com/builds/firefox-stub/en-US/win/5e390326e0ae6db3900bb119921e434b302f3669b8dcd78244fc3da306d067b8/Firefox%20Installer.exe"
F360_URL="https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Client%20Downloader.exe"
for i in "$ISO" 'Firefox Installer.exe' 'Fusion 360 Client Downloader.exe' 'Sciospec EIT Software V1.16.zip' 'Swisstom EIT v2.7.2.zip'; do
    [ -f "$D/$i" ] || rsync --checksum --info=progress2 "aboyle.ca:/var/data/boyle-downloads/$i" "$D/"
done
cat > $D/post-install.bat << EOF
@echo off
title Post Install
echo "Installing Firefox"
"M:\Firefox Installer.exe" -ms -ma
echo "Installing Fusion360"
"M:\Fusion 360 Client Downloader.exe" -i deploy
"C:\Program Files (x86)\Microsoft\Edge\Application\97.0.1072.76\Installer\setup.exe" --uninstall --system-level --force-uninstall
EOF
# TODO unzip and make links for the EIT software
#mklink "Sciospec V1.16" "C:\Sciospec EIT Software V1.16\"
#mklink "Swisstom V2.7.2" "C:\Swisstom EIT v2.7.2"

#VBoxManage list ostypes
#VBoxManage unattended detect --iso="$D/$ISO"
VBoxManage modifyvm $VM --hdd none
VBoxManage unregistervm $VM --delete
if [ "x$(VBoxManage list vms | cut -f1 -d' ' | sed 's/"//g' | grep -m1 "^$VM\$")" != "x$VM" ]; then
    VBoxManage createvm --name $VM --ostype $OS --register
    VBoxManage modifyvm $VM --ioapic on
    VBoxManage modifyvm $VM --memory $MEM --vram 256
    VBoxManage modifyvm $VM --graphicscontroller vboxsvga --accelerate3d on --accelerate2dvideo on
    VBoxManage modifyvm $VM --draganddrop bidirectional --clipboard bidirectional
    VBoxManage createhd --filename "$BASE/$VM/$VM.vdi" --size 80000 --format VDI
    VBoxManage storagectl $VM --name "SATA Controller" --add sata --controller IntelAhci
    VBoxManage storageattach $VM --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "$BASE/$VM/$VM.vdi"
    VBoxManage storagectl $VM --name "IDE Controller" --add ide --controller PIIX4
    VBoxManage modifyvm $VM --boot1 floppy --boot2 dvd --boot3 disk --boot4 none
    VBoxManage modifyvm $VM --cpus $NCPU
    VBoxManage modifyvm $VM --usb on
    VBoxManage modifyvm $VM --usbehci on
    VBoxManage modifyvm $VM --usbxhci on
    VBoxManage sharedfolder add $VM --name downloads --hostpath /var/tmp/downloads --automount --readonly --auto-mount-point="M:"
    VBoxManage unattended install $VM --iso="$D/$ISO" \
        --user "$USER" --password-file="$PASSWDFILE" --full-user-name="$USERNAME" \
        --key="$KEY" \
        --install-additions --additions-iso="/usr/share/virtualbox/VBoxGuestAdditions.iso" \
        --country=CA --time-zone=EST \
        --post-install-command='powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command M:\post-install.bat'
fi
#VBoxHeadless --startvm $VM
