#! /bin/bash -e
echo "add user to {dialout,vboxusers} groups"
for i in dialout vboxusers; do
    (groups $USER | grep -q $i) || sudo usermod -aG $i $USER
done

echo "setup Gnome Terminal settings"
gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Code weight=453 9'
gprofile=$(gsettings get org.gnome.Terminal.ProfilesList default | head -1 | sed "s/'//g")
gschema=org.gnome.Terminal.Legacy.Profile
gpath=/org/gnome/terminal/legacy/profiles:/:${gprofile}/
gsettings set ${gschema}:${gpath} audible-bell false # Ding!
gsettings set ${gschema}:${gpath} use-theme-colors false # Solarized Dark
gsettings set ${gschema}:${gpath} foreground-color 'rgb(131,148,150)'
gsettings set ${gschema}:${gpath} background-color 'rgb(0,43,54)'
gsettings set ${gschema}:${gpath} palette "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"
gsettings set ${gschema}:${gpath} scrollbar-policy 'never'
gsettings set ${gschema}:${gpath} scrollback-unlimited true
gsettings set ${gschema}:${gpath} bold-is-bright true
gsettings set ${gschema}:${gpath} font 'Fira Code 10'
gsettings set ${gschema}:${gpath} use-system-font false
# gsettings list-recursively ${gschema}:${gpath}

echo "setup window manager"
# set background
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/hardy_wallpaper_uhd.png'
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 3700
gsettings set org.gnome.shell.extensions.ding show-drop-place false
gsettings set org.gnome.shell.extensions.ding show-home false
gsettings set org.gnome.shell.extensions.ding add-volumes-opposite false
gsettings set org.gnome.desktop.background show-desktop-icons false

# mouse & keyboard settings
gsettings set org.gnome.desktop.peripherals.touchpad speed 0.25
gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'
gsettings set org.gnome.desktop.peripherals.keyboard delay 259
gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Super>w']"
gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "['<Super>t']"

# setup launcher
gsettings set org.gnome.desktop.interface clock-format 12h
gsettings set org.gtk.Settings.FileChooser clock-format 12h
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position RIGHT
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 24
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
gsettings set org.gnome.shell.extensions.dash-to-dock show-trash false
gnome-extensions enable openweather-extension@jenslody.de
gsettings set org.gnome.shell.extensions.openweather unit celsius
gsettings set org.gnome.shell.extensions.openweather wind-speed-unit knots
gsettings set org.gnome.shell.extensions.openweather pressure-unit kPa
gsettings set org.gnome.shell.extensions.openweather city '45.4211435,-75.6900574>Ottawa, (Old) Ottawa, Ottawa, Eastern Ontario, Ontario, K1P 1J1, Canada >0'
gsettings set org.gnome.shell.extensions.openweather days-forecast 3
gnome-extensions enable system-monitor@paradoxxx.zero.gmail.com

# SSH
echo "restore SSH"
[ -f ~/.ssh/id_rsa ] || ssh-keygen -f ~/.ssh/id_rsa
#eval $(ssh-agent)
#ssh-add

[ -f ~/.ssh/authorized_keys ] || echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDoGpL150gYTove/PA5+FuO6dj8SewqL2XsklHu/U+uk3FNIY8hcG1DuSNo7dF+Gx6tU7E0lLMh5rwW58ps/R2xSY1obNEfypLd+8E6Ql7cXYjKUjae3rxEPiVtjvMxDd9vGqL3I0gXN2GNyoaA+7YYgXMXgRvDnoipNohFkeVL+2jKRbWj+scbIeueTjqfGa8x96YZ+1WytnoBJmXdrw831r76CuFAYbxM03ZqSU+rgJPAqJhL8BQ1uDJxJNdUu5rxKlE0TujXkG+yR3XtCs0oCA01h+r+OeRm1hJAUDntfPjfbkWabBqqcuQD3Ze0zq08RYnURfzerDxRkkk8UJOZ boyle@grendel" | cat ~/.ssh/id_rsa.pub - > ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys

# GPG
key=4994F65E
echo "restore GPG secret key $key"
if [ $(gpg -K $key | wc -l) == 0 ]; then
    ssh -t aboyle.ca 'GPG_TTY=$(tty) gpg-connect-agent updatestartuptty /bye && gpg --export-secret-keys '$key' | (rm -f /tmp/secret.key; umask 0177; cat >/tmp/secret.key)'
    ssh aboyle.ca 'ls -al /tmp/secret.key'
    ssh aboyle.ca 'cat /tmp/secret.key; rm -f /tmp/secret.key' | gpg --import
    echo "$(gpg -K | grep '^ ' | sed 's/^ *//'):6:" | gpg --import-ownertrust
fi

echo "vnc passwd for aboyle.ca"
if [ ! -f ~/.vnc/passwd-aboyle.ca ]; then
    scp aboyle.ca:~/.vnc/passwd-aboyle.ca ~/.vnc/
fi

echo "install firefox extensions"
[ -f /tmp/adblock.xpi ] || wget -O /tmp/adblock.xpi https://addons.mozilla.org/firefox/downloads/file/3877418/
[ -f /tmp/foxyproxy.xpi ] || wget -O /tmp/foxyproxy.xpi https://addons.mozilla.org/firefox/downloads/file/3616824
[ -f /tmp/languagetool.xpi ] || wget -O /tmp/languagetool.xpi https://addons.mozilla.org/firefox/downloads/file/3888056
[ -f /tmp/keepassxc.xpi ] || wget -O /tmp/keepassxc.xpi https://addons.mozilla.org/firefox/downloads/file/3880031
$(dirname $0)/firefox-xpi /tmp/adblock.xpi
$(dirname $0)/firefox-xpi /tmp/foxyproxy.xpi
$(dirname $0)/firefox-xpi /tmp/languagetool.xpi
$(dirname $0)/firefox-xpi /tmp/keepassxc.xpi


echo "setup ~/bash.d for ~/.bashrc"
grep -q '\<bash\.d\>' ~/.bashrc || echo 'for i in $(find ~/.bash.d/ -type f -executable | sort); do source "$i"; done' >> ~/.bashrc
mkdir -p ~/.bash.d
chmod 700 ~/.bash.d

echo "install skel/ to $HOME"
for i in $(find skel -type f | sed 's|^skel/||' | sort); do
    if [ -f ~/$i ]; then
        if diff -q ~/$i skel/$i > /dev/null; then
            echo " - $i: skipped (already exists)"
        else
            echo " ~ $i: skipped (differs from 'skel/')"
        fi
        continue
    fi
    mkdir -p $(dirname $i)
    cp skel/$i ~/$i
    echo " + $i"
done

echo "install vim plugins..."
[ -d ~/.vim/bundle/Vundle.vim ] || \
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
